### ISSUE TITLE
Language problem

### ISSUE THREAD

**Issue by heni015** [xesdoog/Vehicle-Spawner#1]
If we not using difficult language there is option that we must got changed:
Change: `local vehicle_spawner  = gui.get_tab("Vehicle Spawner")`
To: `local vehicle_spawner  = gui.get_tab("GUI_TAB_VEHICLE")`

@EDIT Also you can add new seperated TAB window: `:add_tab("Vehicle Spawner (Gifter)")` but code must be reconstructed

**Comment by xesdoog** [comment]
What do you mean by "*difficult language*" ?

> Change: local vehicle_spawner  = gui.get_tab("Vehicle Spawner")
To: local vehicle_spawner  = gui.get_tab("GUI_TAB_VEHICLE")

That does nothing but place the entire script under YimMenu's vehicle tab which doesn't make any sense because this is a separate script.

> @edit Also you can add new seperated TAB window: :add_tab("Vehicle Spawner (Gifter)") but code must be reconstructed

This is not a vehicle gifter.

**Comment by heni015** [comment]
Maybe in future, but we giving other ppl a car so "giver" :D
I like got every separeted at YIM like Tokyo etc and I also changing this name for @ LUA @ to got it clear, what is what, so only cuz this I like separeted TABs :D
![image](https://github.com/xesdoog/Vehicle-Spawner/assets/49375523/4374b216-a8f5-4dad-bddb-f11bf3f96957)

**Comment by xesdoog** [comment]
Ah, I understand now but this is not an issue with the script.
YimMenu is in charge of loading and setting fonts so without some kind of communication between the script and the menu to instruct it on what language to use, there is no way for Lua devs to change fonts in order to support other languages. I hope that changes in the future because I would love to have language support in all my scripts.
